### ISSUE TITLE
Build missing base image

### ISSUE THREAD

**Issue by bnortman** [eciuca/ubuntu16.04-desktop-dev#1]
\ubuntu16.04-desktop-dev>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'boxcutter/ubuntu1604-desktop' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
The box 'boxcutter/ubuntu1604-desktop' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Vagrant Cloud, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://vagrantcloud.com/boxcutter/ubuntu1604-desktop"]
Error: The requested URL returned error: 404 Not Found

**Comment by eciuca** [comment]
I think it has been renamed from **boxcutter**/ubuntu1604-desktop to **box-cutter**/ubuntu1604-desktop

See https://app.vagrantup.com/box-cutter/boxes/ubuntu1604-desktop

**Comment by eciuca** [comment]
Should be solved by commit e763ed3
